'use strict';
angular.module('pixelRockStudiosApp')
  .factory('portMaster', function () {
    return [{"name": "Star Wars - Playstation 4", "link": "http://www.google.com/", "file": "starwars.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "Call of Duty BOIII - Playstation 4", "link": "http://www.google.com/", "file": "cod.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "Destiny - Playstation 4", "link": "http://www.google.com/", "file": "destiny.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "Sheraton", "link": "http://www.google.com/", "file": "sheraton.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "JBL Headphones", "link": "http://www.google.com/", "file": "jbl.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "Parker Pens", "link": "http://www.google.com/", "file": "parker.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "Seamless 8 Million", "link": "http://www.google.com/", "file": "seamless8m.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "Seamless Avoid Cooking", "link": "http://www.google.com/", "file": "seamlessAC.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "Seamless Pre War", "link": "http://www.google.com/", "file": "seamlessPW.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "Seamless Tiny Kitchen", "link": "http://www.google.com/", "file": "seamlessTK.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "Seamless Your Secret", "link": "http://www.google.com/", "file": "seamlessYS.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "BMW M 40th Anniversary", "link": "http://www.bmwusa.com/m", "file": "bmw_m_40th.json","thumb":"images/portfolio/bmwM40.jpg"},
    {"name": "BMW Motorsports", "link": "http://www.bmwusa.com/standard/content/explore/bmwenthusiasts/bmwmotorsports.aspx", "file": "bmw_motorsports.json","thumb":"images/portfolio/bmwms.jpg"},
    {"name": "BMW ConnectedDrive", "link": "http://www.bmwusa.com/standard/content/innovations/bmwconnecteddrive/connecteddrive.aspx", "file": "bmw_connecteddrive.json","thumb":"images/portfolio/bmwcd.jpg"},
    {"name": "BMW Performance Driving School", "link": "http://www.bmwusa.com/pds","file": "bmw_pds.json","thumb":"images/portfolio/bmwpds.jpg"},
    {"name": "Justin Biebers Collection", "link": "http://www.justinbiebercollectorsedition.com/#home","file": "justin_bieber.json","thumb":"images/portfolio/jb.jpg"},
    {"name": "Biore Skincare", "link": "http://www.biore.com/en-US/biore-skincare", "file": "biore.json","thumb":"images/portfolio/biore.jpg"},
    {"name": "BMW i8 Experience", "link": "http://www.bmwusa.com/standard/content/vehicles/2014/bmwi/bmwi_i8redirect.aspx?from=/Standard/Content/Vehicles/2014/BMWi/BMWi8RD.aspx&return=/Standard/Content/Vehicles/2014/BMWi/BMWi8RD.aspx", "file": "bmw_i8.json","thumb":"images/portfolio/bmwi8.jpg"},
    {"name": "BMW Electronaut", "link": "http://electronaut.bmwactivatethefuture.com/", "file": "bmw_electronaut.json","thumb":"images/portfolio/bmwelec.jpg"},
    {"name": "BMW Naughty or Nice", "link": "http://www.pixelrockstudios.com/work/bmwNN/index.html", "file": "bmw_nn.json","thumb":"images/portfolio/bmwnn.jpg"},
    {"name": "Scholastic - Teach Dear America", "link": "http://www.pixelrockstudios.com/work/TeachDearAmerica/","file": "teachDearAmerica.json","thumb":"images/portfolio/scholastic.jpg"},
    {"name": "Fantastic 4 Rise of the Silver Surfer", "link": "http://www.pixelrockstudios.com/work/f4", "file": "fantastic4.json","thumb":"images/portfolio/f4s.jpg"},
    {"name": "Chevy Flash Calculator", "link": "http://www.pixelrockstudios.com/work/chevy", "file": "chevy_flash.json","thumb":"images/portfolio/chevy.jpg"},
    {"name": "Ritz Carlton White Plains", "link": "http://www.pixelrockstudios.com/work/ritz", "file": "ritz_carlton.json","thumb":"images/portfolio/ritz.jpg"},
    {"name": "Kodak Flash Banner", "link": "http://www.pixelrockstudios.com/work/kodak","file": "kodak_flash.json","thumb":"images/portfolio/kodak.jpg"},
    {"name": "Crestor Astra Zeneca","link": "http://www.pixelrockstudios.com/work/astra","file": "crestor_astra.json","thumb":"images/portfolio/crestor.jpg"},
    {"name": "Gerber", "link": "http://www.pixelrockstudios.com/work/gerber/", "file": "gerber.json","thumb":"images/portfolio/gerber.jpg"},
    {"name": "Fashion Limos", "link": "http://www.pixelrockstudios.com/work/fashionLimo/", "file": "fashionLimo.json","thumb":"images/portfolio/fashionLimo.jpg"},
    {"name": "Scene Ent", "link": "http://www.pixelrockstudios.com/work/Scene-Ent/", "file": "scene.json","thumb":"images/portfolio/sceneEnt.jpg"},
    {"name": "Triumph Realty Funding Corp", "link": "http://www.pixelrockstudios.com/work/Triumph-Realty/", "file": "triumphRealty.json","thumb":"images/portfolio/triumphRealty.jpg"},
    {"name": "Fred Loans", "link": "http://www.pixelrockstudios.com/work/Fred-Loans/", "file": "fredLoans.json","thumb":"images/portfolio/fredLoans.jpg"}
    ]});
